spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimumIdle: 5
      idleTimeout: 30000
      maxLifetime: 180000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true

logging:
  level:
    org:
      hibernate:
        stat: DEBUG
